[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pyliamp"
version = "2.0.0"
description = "Python wrapper of LIA"
readme = "README.md"
license = { text = "MIT" }
authors = [
  { name = "daigokk" }
]
dependencies = [
  "numpy"
]

[project.urls]
Homepage = "https://github.com/daigokk/pyliamp"

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["."]
include = ["pyliamp"]

[tool.setuptools.package-data]
pyliamp = ["pyliamp/bin/lia.exe"]
